### ISSUE TITLE
[Feature]: Toggle Smart Connections in Status Bar?

### ISSUE THREAD

**Issue by paulsalama** [brianpetro/obsidian-smart-connections#1115]
### Problem Statement

I noticed that on the latest update, the Obsidian status bar is now including a Smart Env (with version number).
I like to keep my status bar very minimal (but don't want to remove the status bar entirely). 

### Desired Solution

Can Smart Env be toggled with a button or other setting?

**Comment by brianpetro** [comment]
Hi @paulsalama 

Thanks for the feature request 😊 

A toggle would be a good addition. In the meantime, this CSS snippet should hide it:

```css
.smart-env-status-container {
  display: none;
}
```

https://help.obsidian.md/snippets

🌴

**Comment by Groomingstream9** [comment]
Tried the solution above, it's getting overridden by the constructed stylesheet. 
Worked for me like this:

```css
.smart-env-status-container {
    display: none !important;
}
```
