### ISSUE TITLE
CSS help needed: links are red by default

### ISSUE THREAD

**Issue by pascalandy** [brianpetro/obsidian-smart-connections#482]
I recently installed the Smart Connection (Obsidian) plugin and noticed that its appearance on my system seems unusual, particularly when using the "Things" theme. The links are red by default, which doesn't match the minimal look I desire. This issue appears to be related to CSS customization. Could you please guide me on how to adjust the settings so that it looks more consistent with the rest of my setup? 

### how it looks

<img width="447" alt="SCR-20240227-kaac" src="https://github.com/brianpetro/obsidian-smart-connections/assets/6694151/a28f6d55-f903-49bc-a12f-c9348bb0bd69">

### how it should look

<img width="443" alt="SCR-20240227-kaby" src="https://github.com/brianpetro/obsidian-smart-connections/assets/6694151/0a196a6e-b853-4207-98e5-1c05b0222969">

**Comment by brianpetro** [comment]
@pascalandy the Smart View is designed to inherit styles from your theme.

There have been many updates recently, is it still looking like that with the latest updates?

🌴

**Comment by OleksandrKucherenko** [comment]
```css
a.sc-result-file-title > small {
	color: white !important;
	background-color: #7E57C2 !important;
	font-size: 1rem !important;
	padding: 4px;
}
```

![Image](https://github.com/user-attachments/assets/b06d7dd7-2ffb-4f56-a869-65ef4dafae49)
