### ISSUE TITLE
FR: Add Help Text to the Chat Copy Buttons

### ISSUE THREAD

**Issue by pinuke** [brianpetro/obsidian-smart-connections#81]
### Can We Add Help Texts to the Copy Buttons, Like so:

It's hard to see, but my mouse is over the right button (you can tell, because it's whiter than the other 2)
![image](https://user-images.githubusercontent.com/12621101/227352722-040f5fcb-7789-4ade-be73-51a13539634d.png)
Mouse hover on middle button:
![image](https://user-images.githubusercontent.com/12621101/227352973-06e5cb80-3bf7-449e-b14b-1de2f0b4ec3a.png)
Mouse hover on left button
![image](https://user-images.githubusercontent.com/12621101/227353126-2cac3e6e-c866-4725-93a4-ef5e42c921e8.png)

### Sample CSS Code (That I Injected Into DevTools to Create the Screenshots)

```css
.sc-message.assistant{ 
    position: relative;
}

span.sc-msg-button::after {
    opacity: 0;
    padding: 5px;
    background-color: #0054ad;
    position: absolute;
    top: 100%;
    right: 0;
    transform: translate(-5px,-10px);
    width: fit-content;
    content: "Copy Message";
    white-space: nowrap;
    border-radius: 7px;
    transition: opacity 0.2s;
}

span.sc-msg-button::before {
    opacity: 0;
    contents: " ";
    padding: 5px;
    background-color: #0054ad;
    position: absolute;
    top: 100%;
    right: 0;
    transform: translate(-5px,0);
    width: fit-content;
    content: "This doesn't get displayed, this is just so that the help text button isn't cut off at the bottom of the window";
    white-space: nowrap;
    border-radius: 7px;
    transition: opacity 0.2s;
}

span.sc-msg-button:hover::after{
    opacity: 100%;
}
span.sc-msg-button:nth-of-type(1)::after {
    content: "Copy Context Code Block";
}

span.sc-msg-button:nth-of-type(2)::after {
    content: "Copy Context";
}

span.sc-msg-button:nth-of-type(3)::after {
    content: "Copy Message";
}
```
